# Generated by Django 3.0.4 on 2020-03-31 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, verbose_name='Nome:')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoDeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome:')),
                ('tipo_de_instituicao', models.IntegerField(choices=[(0, 'publica'), (1, 'privada')], default=0)),
                ('endereço', models.CharField(max_length=150, verbose_name='Endereço:')),
            ],
            options={
                'verbose_name': 'Instituição de Saúde',
                'verbose_name_plural': 'Instituições de Saúde',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome:')),
                ('populacao_projetada', models.BigIntegerField(default=0)),
                ('populacao_00_04', models.BigIntegerField(default=0)),
                ('populacao_05_09', models.BigIntegerField(default=0)),
                ('populacao_10_14', models.BigIntegerField(default=0)),
                ('populacao_15_19', models.BigIntegerField(default=0)),
                ('populacao_20_24', models.BigIntegerField(default=0)),
                ('populacao_25_29', models.BigIntegerField(default=0)),
                ('populacao_30_39', models.BigIntegerField(default=0)),
                ('populacao_40_49', models.BigIntegerField(default=0)),
                ('populacao_50_59', models.BigIntegerField(default=0)),
                ('populacao_60_69', models.BigIntegerField(default=0)),
                ('populacao_70', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, verbose_name='Nome:')),
                ('sigla', models.CharField(blank=True, max_length=2, verbose_name='Sigla:')),
            ],
            options={
                'verbose_name': 'Unidade da Feração',
                'verbose_name_plural': 'Undiades da Federação',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeRecursosEmSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_recurso', models.IntegerField(choices=[(0, 'LEITO COVID-19')], default=0)),
                ('quantidade_total', models.IntegerField(verbose_name='Quantidade Total do Recurso:')),
                ('quantidade_disponivel', models.IntegerField(verbose_name='Quantidade do Recurso Disponivel no Momento:')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro:')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.InstituicaoDeSaude', verbose_name='Instituição de Saúde:')),
            ],
            options={
                'verbose_name': 'Registro de Recurso em Saúde',
                'verbose_name_plural': 'Registros de Recursos em Saúde',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeCasosSuspeitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de casos suspeitos no momento:')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro:')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:')),
            ],
            options={
                'verbose_name': 'Registro de Casos Suspeitos',
                'verbose_name_plural': 'Registro de Casos Suspeitos',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeCasoObito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_populacional', models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70')], default=0)),
                ('sexo', models.IntegerField(choices=[(2, 'desconhecido'), (1, 'feminino'), (0, 'masculino')], default=0)),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro:')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:')),
            ],
            options={
                'verbose_name': 'Registro de Caso Obito',
                'verbose_name_plural': 'Registros de Casos Obitos',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeCasoGrave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_populacional', models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70')], default=0)),
                ('sexo', models.IntegerField(choices=[(2, 'desconhecido'), (1, 'feminino'), (0, 'masculino')], default=0)),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro:')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:')),
            ],
            options={
                'verbose_name': 'Registro de Caso Grave',
                'verbose_name_plural': 'Registros de Casos Graves',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeCasoCurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_populacional', models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70')], default=0)),
                ('sexo', models.IntegerField(choices=[(2, 'desconhecido'), (1, 'feminino'), (0, 'masculino')], default=0)),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro:')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:')),
            ],
            options={
                'verbose_name': 'Registro de Caso de Curado:',
                'verbose_name_plural': 'Registros de Casos de Curas:',
            },
        ),
        migrations.CreateModel(
            name='RegistoDeCasoConfirmado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_populacional', models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70')], default=0)),
                ('sexo', models.IntegerField(choices=[(2, 'desconhecido'), (1, 'feminino'), (0, 'masculino')], default=0)),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro:')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:')),
            ],
            options={
                'verbose_name': 'Registro de Caso Confirmado',
                'verbose_name_plural': 'Registros de Casos Confirmados',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.UF', verbose_name='UF:'),
        ),
        migrations.AddField(
            model_name='instituicaodesaude',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='covid19.Municipio', verbose_name='Municipio:'),
        ),
    ]
