# Generated by Django 3.0.5 on 2020-04-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registodecasoconfirmado',
            name='grupo_populacional',
            field=models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70'), (12, 'desconhecido')], default=0),
        ),
        migrations.AlterField(
            model_name='registodecasocurado',
            name='grupo_populacional',
            field=models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70'), (12, 'desconhecido')], default=0),
        ),
        migrations.AlterField(
            model_name='registodecasograve',
            name='grupo_populacional',
            field=models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70'), (12, 'desconhecido')], default=0),
        ),
        migrations.AlterField(
            model_name='registodecasoobito',
            name='grupo_populacional',
            field=models.IntegerField(choices=[(1, 'populacao_00_04'), (2, 'populacao_05_09'), (3, 'populacao_10_14'), (4, 'populacao_15_19'), (5, 'populacao_20_24'), (6, 'populacao_25_29'), (7, 'populacao_30_39'), (8, 'populacao_40_49'), (9, 'populacao_50_59'), (10, 'populacao_60_69'), (11, 'populacao_70'), (12, 'desconhecido')], default=0),
        ),
    ]
